index:
    path: /
    defaults: { _controller: 'App\Controller\Home::index' }

webhook:
    path: /webhook
    defaults: { _controller: 'App\Controller\Webhook::bot' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
